version: "3.7"

services:
    # app (Laravel)
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - redis
        networks:
            - laravel
        platform: linux/amd64  # Força a compatibilidade com x86_64 (se necessário)

    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8989:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - laravel
        platform: linux/amd64  # Força a compatibilidade com x86_64 (se necessário)

    # db mysql
    db:
        image: mysql:5.7.22
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE:-laravel}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
            MYSQL_PASSWORD: ${DB_PASSWORD:-userpass}
            MYSQL_USER: ${DB_USERNAME:-username}
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - "3388:3306"
        networks:
            - laravel
        platform: linux/amd64  # Força a compatibilidade com x86_64 (se necessário)

    # redis
    redis:
        image: redis:alpine
        networks:
            - laravel
        platform: linux/amd64  # Força a compatibilidade com x86_64 (se necessário)

networks:
    laravel:
        driver: bridge
